### ISSUE TITLE
Open seed_groups into new window

### ISSUE THREAD

**Issue by sebasjar** [sarrietav-dev/research-hub#21]
- [x] Create the view
- [x] Open any seed_group into a new window with the specific seed_group_id as .../groups/{seed_group_id}
- [x] Attach the students into the seed_group

**Comment by Fleesin** [comment]
![image](https://github.com/sarrietav-dev/research-hub/assets/77684781/0d428fda-3eff-4d20-beb5-5a89e09295fe)
